FROM --platform=linux/amd64 golang:1.26.2-bookworm AS builder

ENV PATH="/usr/local/go/bin:${PATH}"
ENV GOMAXPROCS=1
ENV GOOS=linux
ENV GOARCH=arm64
ENV CGO_ENABLED=1
ENV CC=aarch64-linux-gnu-gcc
ENV CGO_CFLAGS=-I/usr/aarch64-linux-gnu/include

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc-aarch64-linux-gnu libc6-dev-arm64-cross \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
COPY internal ./internal
RUN go build -p 1 -tags goolm -o /out/mautrix-snapchat-bridgev2 ./cmd/mautrix-snapchat-bridgev2
