package connector

import (
	"context"
	"path/filepath"
	"testing"
	"time"

	sidecar "github.com/colej/mautrix-snapchat/internal/connector"
	"github.com/colej/mautrix-snapchat/internal/snapapi"
	"github.com/colej/mautrix-snapchat/internal/store"
	"maunium.net/go/mautrix/bridgev2"
	"maunium.net/go/mautrix/bridgev2/database"
	"maunium.net/go/mautrix/bridgev2/networkid"
)

func TestBaseSnapchatMessageID(t *testing.T) {
	cases := map[string]string{
		"123":                       "123",
		"123-media-abc":             "123",
		"123-snap-unavailable":      "123",
		"123-edit-abc":              "123",
		"client-456-media-deadbeef": "client-456",
		"  789-media-abc-extra  ":   "789",
		"92639b1c-c6b9-5d4a-b894-a62951708f3b.msg.1407":    "1407",
		"92639b1c-c6b9-5d4a-b894-a62951708f3b.msg.1407-xx": "1407-xx",
	}
	for input, want := range cases {
		if got := baseSnapchatMessageID(input); got != want {
			t.Fatalf("baseSnapchatMessageID(%q) = %q, want %q", input, got, want)
		}
	}
}

func TestParseSnapchatMessageIDAcceptsHydratedIDs(t *testing.T) {
	got, ok := parseSnapchatMessageID("123-media-deadbeef")
	if !ok || got != 123 {
		t.Fatalf("parseSnapchatMessageID hydrated = %d, %t; want 123, true", got, ok)
	}
	got, ok = parseSnapchatMessageID("client-456-media-deadbeef")
	if !ok || got != 456 {
		t.Fatalf("parseSnapchatMessageID client hydrated = %d, %t; want 456, true", got, ok)
	}
	got, ok = parseSnapchatMessageID("92639b1c-c6b9-5d4a-b894-a62951708f3b.msg.1407-media-deadbeef")
	if !ok || got != 1407 {
		t.Fatalf("parseSnapchatMessageID scoped hydrated = %d, %t; want 1407, true", got, ok)
	}
}

func TestScopedSnapchatMessageIDNamespacesByChat(t *testing.T) {
	a := scopedSnapchatMessageID("chat-a", "1407")
	b := scopedSnapchatMessageID("chat-b", "1407")
	if a == b {
		t.Fatalf("scoped ids collided: %q", a)
	}
	if got := baseSnapchatMessageID(a); got != "1407" {
		t.Fatalf("baseSnapchatMessageID(scoped) = %q, want 1407", got)
	}
	if got := scopedSnapchatMessageID("chat-a", a); got != a {
		t.Fatalf("scopedSnapchatMessageID double-scoped %q into %q", a, got)
	}
}

func TestConnectorMessageFromAPIPreservesSnapNotice(t *testing.T) {
	msg := connectorMessageFromAPI(snapapi.Message{
		ID:        "123",
		AuthorID:  "emerson",
		Author:    "Emerson",
		IsSnap:    true,
		Timestamp: time.Date(2026, 5, 17, 12, 0, 0, 0, time.UTC),
	})
	if msg.Text != "New Snap" || !msg.IsSnap {
		t.Fatalf("connector message = text %q isSnap %t, want New Snap true", msg.Text, msg.IsSnap)
	}
	if msg.Timestamp == "" {
		t.Fatal("timestamp was not preserved")
	}
}

func TestNewChatPlaceholderIsNotGenerated(t *testing.T) {
	if isGeneratedSnapchatNotice("New Chat") {
		t.Fatal("New Chat should not be treated as generated by current code paths")
	}
	if !isGeneratedSnapchatNotice("New Snap") {
		t.Fatal("New Snap should remain a notice placeholder")
	}
}

func TestConnectorMessageFromAPIKeepsExternalMediaVisible(t *testing.T) {
	msg := connectorMessageFromAPI(snapapi.Message{
		ID:          "124",
		AuthorID:    "emerson",
		Author:      "Emerson",
		Text:        "Media",
		ContentType: "EXTERNAL_MEDIA",
		Media: []snapapi.MediaAttachment{{
			ID:       "media-1",
			MimeType: "image/jpeg",
			Data:     []byte("fake"),
		}},
	})
	if msg.IsSnap {
		t.Fatal("external media was incorrectly marked as snap")
	}
	if msg.Text != "Media" {
		t.Fatalf("message text = %q, want Media", msg.Text)
	}
}

func TestShouldSuppressAPIMessageSkipsStatusEvents(t *testing.T) {
	if !shouldSuppressAPIMessage(snapapi.Message{ContentType: "STATUS"}, sidecar.Message{Text: "[Snapchat status] STATUS"}) {
		t.Fatal("status API message should be suppressed")
	}
	if shouldSuppressAPIMessage(snapapi.Message{ContentType: "CHAT"}, sidecar.Message{Text: "hello"}) {
		t.Fatal("normal chat API message should not be suppressed")
	}
}

func TestShouldSuppressOutgoingEchoMatchesRecentBody(t *testing.T) {
	sa := &SnapchatAPI{recentOutgoing: map[string][]pendingOutgoing{}}
	sa.recordRecentOutgoing("chat-1", "hello there", "")
	if !sa.shouldSuppressOutgoingEcho("chat-1", sidecar.Message{
		ID:       "1485",
		Text:     "hello there",
		Outgoing: true,
	}) {
		t.Fatal("expected outgoing echo to be suppressed")
	}
	if !sa.shouldSuppressOutgoingEcho("chat-1", sidecar.Message{
		ID:       "1486",
		Text:     "hello there",
		Outgoing: true,
	}) {
		t.Fatal("expected repeated API echo to be suppressed within the outgoing TTL")
	}
	if sa.shouldSuppressOutgoingEcho("chat-1", sidecar.Message{
		ID:       "1487",
		Text:     "different text",
		Outgoing: true,
	}) {
		t.Fatal("unexpected suppression for non-matching body")
	}
}

func TestShouldNotSuppressLaterSnapchatAppSendWithSameBody(t *testing.T) {
	sa := &SnapchatAPI{recentOutgoing: map[string][]pendingOutgoing{
		"chat-1": {{
			Body:   normalizeOutgoingBody("hello there"),
			SentAt: time.Now().Add(-2 * time.Minute),
		}},
	}}
	if sa.shouldSuppressOutgoingEcho("chat-1", sidecar.Message{
		ID:       "1488",
		Text:     "hello there",
		Outgoing: true,
	}) {
		t.Fatal("Snapchat app send with repeated text should not be suppressed after the short text-only echo window")
	}
}

func TestNormalizeRemoteMessageDirectionTreatsLoginLabelAsSelf(t *testing.T) {
	sa := &SnapchatAPI{Label: "browser-session"}
	msg := sa.normalizeRemoteMessageDirection("chat-1", sidecar.Message{
		ID:       "m1",
		AuthorID: "browser-session",
		Author:   "browser-session",
		Text:     "sent from Snapchat Web",
	})
	if !msg.Outgoing {
		t.Fatal("browser-session-authored message should be treated as outgoing")
	}
	if msg.Author != "You" {
		t.Fatalf("author = %q, want You", msg.Author)
	}
}

func TestNormalizeAPIMessageDirectionTreatsSavedSelfIDAsSelf(t *testing.T) {
	db, err := store.New(filepath.Join(t.TempDir(), "state.sqlite"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if err = db.UpsertAPISyncState(store.APISyncState{
		UserID:            "browser-session",
		SelfUserID:        "7c4091a5-5231-441c-9c41-a80dfb6e805f",
		ConversationState: map[string]int64{},
	}); err != nil {
		t.Fatal(err)
	}
	sa := &SnapchatAPI{
		Label:     "browser-session",
		Connector: &SnapchatConnector{store: db},
	}
	msg := sa.normalizeAPIMessageDirection("chat-1", snapapi.Message{
		ID:       "m2",
		AuthorID: "7c4091a5-5231-441c-9c41-a80dfb6e805f",
		Author:   "Cole",
		Text:     "sent from Snapchat mobile",
	})
	if !msg.Outgoing {
		t.Fatal("saved-self authored API message should be treated as outgoing")
	}
}

func TestIsThisUserRecognizesSavedSelfID(t *testing.T) {
	db, err := store.New(filepath.Join(t.TempDir(), "state.sqlite"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if err = db.UpsertAPISyncState(store.APISyncState{
		UserID:            "browser-session",
		SelfUserID:        "7c4091a5-5231-441c-9c41-a80dfb6e805f",
		ConversationState: map[string]int64{},
	}); err != nil {
		t.Fatal(err)
	}
	sa := &SnapchatAPI{
		Label:     "browser-session",
		Connector: &SnapchatConnector{store: db},
	}
	if !sa.IsThisUser(nil, makeUserID("7c4091a5-5231-441c-9c41-a80dfb6e805f")) {
		t.Fatal("saved Snapchat self ID should be recognized as this user")
	}
}

func TestDisappearingSettingForMessageSkipsSavedMessages(t *testing.T) {
	sa := &SnapchatAPI{chatDisappearAfter: map[string]int64{"chat-1": 10}}
	got := sa.disappearingSettingForMessage("chat-1", sidecar.Message{
		ID:                    "m1",
		Text:                  "unsaved",
		DisappearAfterSeconds: 20,
	})
	if got.Timer != 20*time.Second {
		t.Fatalf("message disappearing timer = %s, want 20s", got.Timer)
	}
	got = sa.disappearingSettingForMessage("chat-1", sidecar.Message{
		ID:    "m2",
		Text:  "saved",
		Saved: true,
	})
	if got.Timer != 0 {
		t.Fatalf("saved message got disappearing timer %s", got.Timer)
	}
	got = sa.disappearingSettingForMessage("chat-1", sidecar.Message{
		ID:   "m3",
		Text: "chat default",
	})
	if got.Timer != 10*time.Second {
		t.Fatalf("chat disappearing timer = %s, want 10s", got.Timer)
	}
}

func TestRememberChatDisappearKeepsKnownTimerWhenInputMissing(t *testing.T) {
	sa := &SnapchatAPI{
		chatsByID:          map[string]chatRef{"chat-1": {ID: "chat-1", DisappearAfterSeconds: 10}},
		chatDisappearAfter: map[string]int64{"chat-1": 10},
	}
	if changed := sa.rememberChatDisappear("chat-1", 0); changed {
		t.Fatal("zero retention should not report a changed timer")
	}
	if got := sa.disappearingSettingForChat("chat-1"); got == nil || got.Timer != 10*time.Second {
		t.Fatalf("known disappearing timer was cleared: %#v", got)
	}
}

func TestRememberChatDisappearReportsTimerChangeForPortalResync(t *testing.T) {
	sa := &SnapchatAPI{
		chatsByID:          map[string]chatRef{},
		chatDisappearAfter: map[string]int64{},
	}
	if changed := sa.rememberChatDisappear("chat-1", 60); !changed {
		t.Fatal("new retention timer should report a change")
	}
	if changed := sa.rememberChatDisappear("chat-1", 60); changed {
		t.Fatal("same retention timer should not report a change")
	}
}

func TestForgetChatDisappearClearsKnownTimer(t *testing.T) {
	sa := &SnapchatAPI{
		chatsByID:          map[string]chatRef{"chat-1": {ID: "chat-1", DisappearAfterSeconds: 60}},
		chatDisappearAfter: map[string]int64{"chat-1": 60},
	}
	if changed := sa.forgetChatDisappear("chat-1"); !changed {
		t.Fatal("clearing a known timer should report a change")
	}
	if got := sa.disappearingSettingForChat("chat-1"); got != nil {
		t.Fatalf("disappearing timer was not cleared: %#v", got)
	}
	if changed := sa.forgetChatDisappear("chat-1"); changed {
		t.Fatal("clearing an already empty timer should not report a change")
	}
}

func TestChatInfoUsesRememberedRetention(t *testing.T) {
	sa := &SnapchatAPI{
		Label:              "browser-session",
		chatsByID:          map[string]chatRef{"chat-1": {ID: "chat-1", Name: "Emerson"}},
		ghostNames:         map[string]string{},
		ghostUsernames:     map[string]string{},
		chatDisappearAfter: map[string]int64{"chat-1": 86400},
	}
	info := sa.chatInfoFor("chat-1", "Emerson")
	if info == nil || info.Disappear == nil {
		t.Fatal("chat info should include disappearing settings")
	}
	if info.Disappear.Timer != 24*time.Hour {
		t.Fatalf("chat disappear timer = %s, want 24h", info.Disappear.Timer)
	}
}

func TestConnectorMessageFromAPIPreservesDisappearForTextAndReply(t *testing.T) {
	for _, tc := range []struct {
		name   string
		quoted int64
	}{
		{name: "normal text"},
		{name: "reply", quoted: 123},
	} {
		t.Run(tc.name, func(t *testing.T) {
			msg := connectorMessageFromAPI(snapapi.Message{
				ID:              "456",
				AuthorID:        "emerson",
				Author:          "Emerson",
				Text:            "hello",
				ContentType:     "CHAT",
				DisappearAfter:  24 * time.Hour,
				QuotedMessageID: tc.quoted,
			})
			if msg.DisappearAfterSeconds != 86400 {
				t.Fatalf("disappear after = %d, want 86400", msg.DisappearAfterSeconds)
			}
			if tc.quoted > 0 && msg.QuotedMessageID != "123" {
				t.Fatalf("quoted id = %q, want 123", msg.QuotedMessageID)
			}
		})
	}
}

func TestConvertMessageAppliesDisappearToTextReplyAndSelfEcho(t *testing.T) {
	sa := &SnapchatAPI{
		Label:              "browser-session",
		chatsByID:          map[string]chatRef{"chat-1": {ID: "chat-1", Name: "Emerson"}},
		ghostNames:         map[string]string{},
		chatDisappearAfter: map[string]int64{"chat-1": 86400},
	}
	portal := &bridgev2.Portal{Portal: &database.Portal{
		PortalKey: networkid.PortalKey{ID: networkid.PortalID("chat-1")},
	}}
	for _, tc := range []struct {
		name    string
		message sidecar.Message
	}{
		{name: "incoming text", message: sidecar.Message{ID: "1", Author: "Emerson", Text: "hello"}},
		{name: "incoming reply", message: sidecar.Message{ID: "2", Author: "Emerson", Text: "reply", QuotedMessageID: "1"}},
		{name: "self sync echo", message: sidecar.Message{ID: "3", Author: "You", Text: "from snapchat", Outgoing: true}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			converted, err := sa.convertMessage(context.Background(), portal, nil, tc.message)
			if err != nil {
				t.Fatal(err)
			}
			if converted.Disappear.Timer != 24*time.Hour {
				t.Fatalf("converted disappear timer = %s, want 24h", converted.Disappear.Timer)
			}
		})
	}
}

func TestConvertMessageSuppressesDisappearForSavedMessages(t *testing.T) {
	sa := &SnapchatAPI{chatDisappearAfter: map[string]int64{"chat-1": 86400}}
	portal := &bridgev2.Portal{Portal: &database.Portal{
		PortalKey: networkid.PortalKey{ID: networkid.PortalID("chat-1")},
	}}
	converted, err := sa.convertMessage(context.Background(), portal, nil, sidecar.Message{
		ID:     "1",
		Author: "Emerson",
		Text:   "saved",
		Saved:  true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if converted.Disappear.Timer != 0 {
		t.Fatalf("saved converted message got disappearing timer %s", converted.Disappear.Timer)
	}
}

func TestShouldQueueMessageEditDetectsDecryptedBodyLater(t *testing.T) {
	if !shouldQueueMessageEdit(&store.MessageState{
		Text: "Snapchat message unavailable",
		Kind: "chat",
	}, sidecar.Message{Text: "now decoded"}) {
		t.Fatal("expected plaintext replacement to queue a Matrix edit")
	}
}

func TestShouldQueueMessageEditSkipsDuplicatesAndEmptyBodies(t *testing.T) {
	if shouldQueueMessageEdit(nil, sidecar.Message{Text: "new"}) {
		t.Fatal("nil baseline should not queue an edit")
	}
	if shouldQueueMessageEdit(&store.MessageState{Text: "same", Kind: "chat"}, sidecar.Message{Text: " same "}) {
		t.Fatal("same normalized text should not queue an edit")
	}
	if shouldQueueMessageEdit(&store.MessageState{Text: "old", Kind: "chat"}, sidecar.Message{}) {
		t.Fatal("empty replacement should not queue an edit")
	}
}

func TestShouldQueueMessageEditSkipsSnapAndMediaRows(t *testing.T) {
	for _, state := range []*store.MessageState{
		{Text: "New Snap", Kind: "snap"},
		{Text: "photo.jpg", Kind: "media"},
		{Text: "caption", Kind: "chat", HasMedia: true},
	} {
		if shouldQueueMessageEdit(state, sidecar.Message{Text: "decoded"}) {
			t.Fatalf("state %+v should not queue an ordinary text edit", state)
		}
	}
}

func TestClassifyMessageSync(t *testing.T) {
	if got := classifyMessageSync(nil, sidecar.Message{ID: "1", Text: "hello"}); got != messageSyncNew {
		t.Fatalf("nil existing classify = %s, want %s", got, messageSyncNew)
	}
	if got := classifyMessageSync(&store.MessageState{Text: "old text", Kind: "chat"}, sidecar.Message{ID: "1", Text: "new text"}); got != messageSyncEdit {
		t.Fatalf("changed text classify = %s, want %s", got, messageSyncEdit)
	}
	if got := classifyMessageSync(&store.MessageState{Text: "same text", Kind: "chat"}, sidecar.Message{ID: "1", Text: " same text "}); got != messageSyncUnchanged {
		t.Fatalf("same text classify = %s, want %s", got, messageSyncUnchanged)
	}
	if got := classifyMessageSync(&store.MessageState{Text: "photo.jpg", Kind: "media"}, sidecar.Message{ID: "1", Text: "caption changed"}); got != messageSyncUnchanged {
		t.Fatalf("media text classify = %s, want %s", got, messageSyncUnchanged)
	}
}

func TestClassifyMessageSyncTreatsDelayedDecryptionAsEdit(t *testing.T) {
	got := classifyMessageSync(&store.MessageState{
		Text: "[Snapchat message unavailable]",
		Kind: "chat",
	}, sidecar.Message{ID: "1", Text: "finally decoded"})
	if got != messageSyncEdit {
		t.Fatalf("delayed decrypt classify = %s, want %s", got, messageSyncEdit)
	}
}

func TestSuppressUndecryptedBackfillSkipsOnlyNewHistoricalPlaceholders(t *testing.T) {
	placeholder := sidecar.Message{ID: "123", Text: "[Snapchat message unavailable]"}
	apiMessage := snapapi.Message{ID: "123", ContentType: "CHAT"}
	if !suppressUndecryptedBackfill("startup stored portal backfill", nil, placeholder, apiMessage) {
		t.Fatal("expected new historical undecrypted placeholder to be suppressed")
	}
	if suppressUndecryptedBackfill("api poll", nil, placeholder, apiMessage) {
		t.Fatal("live API poll placeholder should not be suppressed")
	}
	if suppressUndecryptedBackfill("startup stored portal backfill", &store.MessageState{Text: "old"}, placeholder, apiMessage) {
		t.Fatal("stored baseline should not be suppressed")
	}
	if suppressUndecryptedBackfill("startup stored portal backfill", nil, sidecar.Message{ID: "124", Text: "decoded"}, snapapi.Message{ID: "124", ContentType: "CHAT"}) {
		t.Fatal("decoded historical text should not be suppressed")
	}
}

func TestSuppressUndecryptedBackfillKeepsSnapsAndMediaVisible(t *testing.T) {
	if suppressUndecryptedBackfill("startup stored portal backfill", nil, sidecar.Message{ID: "123", Text: "New Snap", IsSnap: true}, snapapi.Message{ID: "123", IsSnap: true}) {
		t.Fatal("snap placeholder should stay visible")
	}
	if suppressUndecryptedBackfill("startup stored portal backfill", nil, sidecar.Message{ID: "124", Text: "[Snapchat message unavailable]"}, snapapi.Message{
		ID:          "124",
		Media:       []snapapi.MediaAttachment{{ID: "m1"}},
		ContentType: "EXTERNAL_MEDIA",
	}) {
		t.Fatal("media placeholder should stay visible")
	}
}

func TestRestoreStoredDecryptedTextUsesStableTextForTransientEELFailure(t *testing.T) {
	got, ok := restoreStoredDecryptedText(&store.MessageState{
		Text: "decoded earlier",
		Kind: "chat",
	}, sidecar.Message{
		ID:   "123",
		Text: "[Snapchat message unavailable]",
	}, snapapi.Message{
		ID:          "123",
		ContentType: "CHAT",
	})
	if !ok || got != "decoded earlier" {
		t.Fatalf("restoreStoredDecryptedText = %q, %t; want decoded earlier, true", got, ok)
	}
}

func TestRestoreStoredDecryptedTextDoesNotRestoreGeneratedOrMediaText(t *testing.T) {
	cases := []struct {
		name     string
		existing *store.MessageState
		message  sidecar.Message
		api      snapapi.Message
	}{
		{
			name:     "existing notice",
			existing: &store.MessageState{Text: "New Snap", Kind: "chat"},
			message:  sidecar.Message{ID: "123", Text: "[Snapchat message unavailable]"},
			api:      snapapi.Message{ID: "123", ContentType: "CHAT"},
		},
		{
			name:     "new text already decoded",
			existing: &store.MessageState{Text: "decoded earlier", Kind: "chat"},
			message:  sidecar.Message{ID: "123", Text: "decoded now"},
			api:      snapapi.Message{ID: "123", ContentType: "CHAT"},
		},
		{
			name:     "snap",
			existing: &store.MessageState{Text: "decoded earlier", Kind: "chat"},
			message:  sidecar.Message{ID: "123", Text: "[Snapchat message unavailable]", IsSnap: true},
			api:      snapapi.Message{ID: "123", IsSnap: true},
		},
		{
			name:     "stored media",
			existing: &store.MessageState{Text: "caption", Kind: "media"},
			message:  sidecar.Message{ID: "123", Text: "[Snapchat message unavailable]"},
			api:      snapapi.Message{ID: "123", ContentType: "CHAT"},
		},
		{
			name:     "incoming media",
			existing: &store.MessageState{Text: "caption", Kind: "chat"},
			message:  sidecar.Message{ID: "123", Text: "[Snapchat message unavailable]"},
			api:      snapapi.Message{ID: "123", ContentType: "EXTERNAL_MEDIA", Media: []snapapi.MediaAttachment{{ID: "m1"}}},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got, ok := restoreStoredDecryptedText(tc.existing, tc.message, tc.api); ok {
				t.Fatalf("restoreStoredDecryptedText unexpectedly restored %q", got)
			}
		})
	}
}

func TestShouldSendReadReceiptToSnapchatSkipsExactUnknownTargets(t *testing.T) {
	if (&SnapchatAPI{}).shouldSendReadReceiptToSnapchat("chat-1", 123, true) {
		t.Fatal("exact read receipt with no stored baseline should be skipped")
	}
}

func TestShouldSendReadReceiptToSnapchatAllowsStoredText(t *testing.T) {
	db, err := store.New(filepath.Join(t.TempDir(), "state.sqlite"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if err = db.UpsertMessages([]store.MessageState{{
		PortalKey:  "chat-1",
		RemoteID:   "123",
		Text:       "hello",
		Kind:       "chat",
		LastSeenAt: time.Now(),
	}}); err != nil {
		t.Fatal(err)
	}
	sa := &SnapchatAPI{Connector: &SnapchatConnector{store: db}}
	if !sa.shouldSendReadReceiptToSnapchat("chat-1", 123, true) {
		t.Fatal("stored chat text should be safe for read receipt")
	}
}

func TestShouldSendReadReceiptToSnapchatSkipsSnapAndMediaTargets(t *testing.T) {
	db, err := store.New(filepath.Join(t.TempDir(), "state.sqlite"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if err = db.UpsertMessages([]store.MessageState{
		{PortalKey: "chat-1", RemoteID: "123", Text: "New Snap", Kind: "snap", LastSeenAt: time.Now()},
		{PortalKey: "chat-1", RemoteID: "124", Text: "photo.jpg", Kind: "media", LastSeenAt: time.Now()},
		{PortalKey: "chat-1", RemoteID: "125", Text: "caption", Kind: "chat", HasMedia: true, LastSeenAt: time.Now()},
	}); err != nil {
		t.Fatal(err)
	}
	sa := &SnapchatAPI{Connector: &SnapchatConnector{store: db}}
	for _, messageID := range []int64{123, 124, 125} {
		if sa.shouldSendReadReceiptToSnapchat("chat-1", messageID, true) {
			t.Fatalf("message %d should be skipped for safe read receipts", messageID)
		}
	}
}
