package connector

import (
	"path/filepath"
	"strings"
	"testing"
	"time"

	sidecar "github.com/colej/mautrix-snapchat/internal/connector"
	"github.com/colej/mautrix-snapchat/internal/snapapi"
	"github.com/colej/mautrix-snapchat/internal/store"
)

func TestBaseSnapchatMessageID(t *testing.T) {
	cases := map[string]string{
		"123":                       "123",
		"123-media-abc":             "123",
		"123-snap-unavailable":      "123",
		"123-edit-abc":              "123",
		"client-456-media-deadbeef": "client-456",
		"  789-media-abc-extra  ":   "789",
		"92639b1c-c6b9-5d4a-b894-a62951708f3b.msg.1407":    "1407",
		"92639b1c-c6b9-5d4a-b894-a62951708f3b.msg.1407-xx": "1407-xx",
	}
	for input, want := range cases {
		if got := baseSnapchatMessageID(input); got != want {
			t.Fatalf("baseSnapchatMessageID(%q) = %q, want %q", input, got, want)
		}
	}
}

func TestParseSnapchatMessageIDAcceptsHydratedIDs(t *testing.T) {
	got, ok := parseSnapchatMessageID("123-media-deadbeef")
	if !ok || got != 123 {
		t.Fatalf("parseSnapchatMessageID hydrated = %d, %t; want 123, true", got, ok)
	}
	got, ok = parseSnapchatMessageID("client-456-media-deadbeef")
	if !ok || got != 456 {
		t.Fatalf("parseSnapchatMessageID client hydrated = %d, %t; want 456, true", got, ok)
	}
	got, ok = parseSnapchatMessageID("92639b1c-c6b9-5d4a-b894-a62951708f3b.msg.1407-media-deadbeef")
	if !ok || got != 1407 {
		t.Fatalf("parseSnapchatMessageID scoped hydrated = %d, %t; want 1407, true", got, ok)
	}
}

func TestScopedSnapchatMessageIDNamespacesByChat(t *testing.T) {
	a := scopedSnapchatMessageID("chat-a", "1407")
	b := scopedSnapchatMessageID("chat-b", "1407")
	if a == b {
		t.Fatalf("scoped ids collided: %q", a)
	}
	if got := baseSnapchatMessageID(a); got != "1407" {
		t.Fatalf("baseSnapchatMessageID(scoped) = %q, want 1407", got)
	}
	if got := scopedSnapchatMessageID("chat-a", a); got != a {
		t.Fatalf("scopedSnapchatMessageID double-scoped %q into %q", a, got)
	}
}

func TestConnectorMessageFromAPIPreservesSnapNotice(t *testing.T) {
	msg := connectorMessageFromAPI(snapapi.Message{
		ID:        "123",
		AuthorID:  "emerson",
		Author:    "Emerson",
		IsSnap:    true,
		Timestamp: time.Date(2026, 5, 17, 12, 0, 0, 0, time.UTC),
	})
	if msg.Text != "New Snap" || !msg.IsSnap {
		t.Fatalf("connector message = text %q isSnap %t, want New Snap true", msg.Text, msg.IsSnap)
	}
	if msg.Timestamp == "" {
		t.Fatal("timestamp was not preserved")
	}
}

func TestNewChatPlaceholderIsNotGenerated(t *testing.T) {
	if isGeneratedSnapchatNotice("New Chat") {
		t.Fatal("New Chat should not be treated as generated by current code paths")
	}
	if !isGeneratedSnapchatNotice("New Snap") {
		t.Fatal("New Snap should remain a notice placeholder")
	}
}

func TestConnectorMessageFromAPIKeepsExternalMediaVisible(t *testing.T) {
	msg := connectorMessageFromAPI(snapapi.Message{
		ID:          "124",
		AuthorID:    "emerson",
		Author:      "Emerson",
		Text:        "Media",
		ContentType: "EXTERNAL_MEDIA",
		Media: []snapapi.MediaAttachment{{
			ID:       "media-1",
			MimeType: "image/jpeg",
			Data:     []byte("fake"),
		}},
	})
	if msg.IsSnap {
		t.Fatal("external media was incorrectly marked as snap")
	}
	if msg.Text != "Media" {
		t.Fatalf("message text = %q, want Media", msg.Text)
	}
}

func TestShouldSuppressOutgoingEchoMatchesRecentBody(t *testing.T) {
	sa := &SnapchatAPI{recentOutgoing: map[string][]pendingOutgoing{}}
	sa.recordRecentOutgoing("chat-1", "hello there", "")
	if !sa.shouldSuppressOutgoingEcho("chat-1", sidecar.Message{
		ID:       "1485",
		Text:     "hello there",
		Outgoing: true,
	}) {
		t.Fatal("expected outgoing echo to be suppressed")
	}
	if !sa.shouldSuppressOutgoingEcho("chat-1", sidecar.Message{
		ID:       "1486",
		Text:     "hello there",
		Outgoing: true,
	}) {
		t.Fatal("expected repeated API echo to be suppressed within the outgoing TTL")
	}
	if sa.shouldSuppressOutgoingEcho("chat-1", sidecar.Message{
		ID:       "1487",
		Text:     "different text",
		Outgoing: true,
	}) {
		t.Fatal("unexpected suppression for non-matching body")
	}
}

func TestDisappearingSettingForMessageSkipsSavedMessages(t *testing.T) {
	sa := &SnapchatAPI{chatDisappearAfter: map[string]int64{"chat-1": 10}}
	got := sa.disappearingSettingForMessage("chat-1", sidecar.Message{
		ID:                    "m1",
		Text:                  "unsaved",
		DisappearAfterSeconds: 20,
	})
	if got.Timer != 20*time.Second {
		t.Fatalf("message disappearing timer = %s, want 20s", got.Timer)
	}
	got = sa.disappearingSettingForMessage("chat-1", sidecar.Message{
		ID:    "m2",
		Text:  "saved",
		Saved: true,
	})
	if got.Timer != 0 {
		t.Fatalf("saved message got disappearing timer %s", got.Timer)
	}
	got = sa.disappearingSettingForMessage("chat-1", sidecar.Message{
		ID:   "m3",
		Text: "chat default",
	})
	if got.Timer != 10*time.Second {
		t.Fatalf("chat disappearing timer = %s, want 10s", got.Timer)
	}
}

func TestSnapchatCookieStringAcceptsAuthSession(t *testing.T) {
	got, err := snapchatCookieString(map[string]string{
		"__Host-sc-a-nonce":           "nonce",
		"__Host-sc-a-auth-session":    "session",
		"__Host-X-Snap-Client-Cookie": "client",
	})
	if err != nil {
		t.Fatal(err)
	}
	if got != "__Host-sc-a-nonce=nonce; __Host-sc-a-auth-session=session; __Host-X-Snap-Client-Cookie=client" {
		t.Fatalf("cookie string = %q", got)
	}
}

func TestSnapchatCookieStringRejectsMissingSecretsWithoutLeakingValues(t *testing.T) {
	_, err := snapchatCookieString(map[string]string{
		"__Host-sc-a-nonce": "super-secret-nonce",
	})
	if err == nil {
		t.Fatal("expected missing cookie error")
	}
	if strings.Contains(err.Error(), "super-secret-nonce") {
		t.Fatal("error leaked cookie value")
	}
}

func TestShouldSendReadReceiptDedupesDurably(t *testing.T) {
	db, err := store.New(filepath.Join(t.TempDir(), "state.sqlite"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	sa := &SnapchatAPI{Connector: &SnapchatConnector{store: db}}
	if !sa.shouldSendReadReceipt("chat-1", 100) {
		t.Fatal("first read receipt should be allowed")
	}
	sa.markReadReceiptSent("chat-1", 100, 5)
	if sa.shouldSendReadReceipt("chat-1", 100) {
		t.Fatal("duplicate read receipt should be skipped")
	}
	if !sa.shouldSendReadReceipt("chat-1", 101) {
		t.Fatal("newer read receipt should be allowed")
	}
}

func TestShouldSendReadReceiptSkipsStoredSnap(t *testing.T) {
	db, err := store.New(filepath.Join(t.TempDir(), "state.sqlite"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if err = db.UpsertMessages([]store.MessageState{{
		PortalKey: "chat-1",
		RemoteID:  "200",
		Kind:      "snap",
	}}); err != nil {
		t.Fatal(err)
	}
	sa := &SnapchatAPI{Connector: &SnapchatConnector{store: db}}
	if sa.shouldSendReadReceipt("chat-1", 200) {
		t.Fatal("snap placeholder should not be marked read")
	}
}

func TestShouldSendTypingDebounces(t *testing.T) {
	sa := &SnapchatAPI{
		Connector:      &SnapchatConnector{Config: ConnectorConfig{TypingDebounceSeconds: 60}},
		lastTypingSent: make(map[string]time.Time),
	}
	if !sa.shouldSendTyping("chat-1") {
		t.Fatal("first typing notification should be allowed")
	}
	if sa.shouldSendTyping("chat-1") {
		t.Fatal("second typing notification inside debounce should be skipped")
	}
}
