package connector

import (
	"path/filepath"
	"testing"
	"time"

	sidecar "github.com/colej/mautrix-snapchat/internal/connector"
	"github.com/colej/mautrix-snapchat/internal/snapapi"
	"github.com/colej/mautrix-snapchat/internal/store"
)

func TestBaseSnapchatMessageID(t *testing.T) {
	cases := map[string]string{
		"123":                       "123",
		"123-media-abc":             "123",
		"123-snap-unavailable":      "123",
		"123-edit-abc":              "123",
		"client-456-media-deadbeef": "client-456",
		"  789-media-abc-extra  ":   "789",
		"92639b1c-c6b9-5d4a-b894-a62951708f3b.msg.1407":    "1407",
		"92639b1c-c6b9-5d4a-b894-a62951708f3b.msg.1407-xx": "1407-xx",
	}
	for input, want := range cases {
		if got := baseSnapchatMessageID(input); got != want {
			t.Fatalf("baseSnapchatMessageID(%q) = %q, want %q", input, got, want)
		}
	}
}

func TestParseSnapchatMessageIDAcceptsHydratedIDs(t *testing.T) {
	got, ok := parseSnapchatMessageID("123-media-deadbeef")
	if !ok || got != 123 {
		t.Fatalf("parseSnapchatMessageID hydrated = %d, %t; want 123, true", got, ok)
	}
	got, ok = parseSnapchatMessageID("client-456-media-deadbeef")
	if !ok || got != 456 {
		t.Fatalf("parseSnapchatMessageID client hydrated = %d, %t; want 456, true", got, ok)
	}
	got, ok = parseSnapchatMessageID("92639b1c-c6b9-5d4a-b894-a62951708f3b.msg.1407-media-deadbeef")
	if !ok || got != 1407 {
		t.Fatalf("parseSnapchatMessageID scoped hydrated = %d, %t; want 1407, true", got, ok)
	}
}

func TestScopedSnapchatMessageIDNamespacesByChat(t *testing.T) {
	a := scopedSnapchatMessageID("chat-a", "1407")
	b := scopedSnapchatMessageID("chat-b", "1407")
	if a == b {
		t.Fatalf("scoped ids collided: %q", a)
	}
	if got := baseSnapchatMessageID(a); got != "1407" {
		t.Fatalf("baseSnapchatMessageID(scoped) = %q, want 1407", got)
	}
	if got := scopedSnapchatMessageID("chat-a", a); got != a {
		t.Fatalf("scopedSnapchatMessageID double-scoped %q into %q", a, got)
	}
}

func TestConnectorMessageFromAPIPreservesSnapNotice(t *testing.T) {
	msg := connectorMessageFromAPI(snapapi.Message{
		ID:        "123",
		AuthorID:  "emerson",
		Author:    "Emerson",
		IsSnap:    true,
		Timestamp: time.Date(2026, 5, 17, 12, 0, 0, 0, time.UTC),
	})
	if msg.Text != "New Snap" || !msg.IsSnap {
		t.Fatalf("connector message = text %q isSnap %t, want New Snap true", msg.Text, msg.IsSnap)
	}
	if msg.Timestamp == "" {
		t.Fatal("timestamp was not preserved")
	}
}

func TestNewChatPlaceholderIsNotGenerated(t *testing.T) {
	if isGeneratedSnapchatNotice("New Chat") {
		t.Fatal("New Chat should not be treated as generated by current code paths")
	}
	if !isGeneratedSnapchatNotice("New Snap") {
		t.Fatal("New Snap should remain a notice placeholder")
	}
}

func TestConnectorMessageFromAPIKeepsExternalMediaVisible(t *testing.T) {
	msg := connectorMessageFromAPI(snapapi.Message{
		ID:          "124",
		AuthorID:    "emerson",
		Author:      "Emerson",
		Text:        "Media",
		ContentType: "EXTERNAL_MEDIA",
		Media: []snapapi.MediaAttachment{{
			ID:       "media-1",
			MimeType: "image/jpeg",
			Data:     []byte("fake"),
		}},
	})
	if msg.IsSnap {
		t.Fatal("external media was incorrectly marked as snap")
	}
	if msg.Text != "Media" {
		t.Fatalf("message text = %q, want Media", msg.Text)
	}
}

func TestShouldSuppressOutgoingEchoMatchesRecentBody(t *testing.T) {
	sa := &SnapchatAPI{recentOutgoing: map[string][]pendingOutgoing{}}
	sa.recordRecentOutgoing("chat-1", "hello there", "")
	if !sa.shouldSuppressOutgoingEcho("chat-1", sidecar.Message{
		ID:       "1485",
		Text:     "hello there",
		Outgoing: true,
	}) {
		t.Fatal("expected outgoing echo to be suppressed")
	}
	if !sa.shouldSuppressOutgoingEcho("chat-1", sidecar.Message{
		ID:       "1486",
		Text:     "hello there",
		Outgoing: true,
	}) {
		t.Fatal("expected repeated API echo to be suppressed within the outgoing TTL")
	}
	if sa.shouldSuppressOutgoingEcho("chat-1", sidecar.Message{
		ID:       "1487",
		Text:     "different text",
		Outgoing: true,
	}) {
		t.Fatal("unexpected suppression for non-matching body")
	}
}

func TestShouldNotSuppressLaterSnapchatAppSendWithSameBody(t *testing.T) {
	sa := &SnapchatAPI{recentOutgoing: map[string][]pendingOutgoing{
		"chat-1": {{
			Body:   normalizeOutgoingBody("hello there"),
			SentAt: time.Now().Add(-2 * time.Minute),
		}},
	}}
	if sa.shouldSuppressOutgoingEcho("chat-1", sidecar.Message{
		ID:       "1488",
		Text:     "hello there",
		Outgoing: true,
	}) {
		t.Fatal("Snapchat app send with repeated text should not be suppressed after the short text-only echo window")
	}
}

func TestNormalizeRemoteMessageDirectionTreatsLoginLabelAsSelf(t *testing.T) {
	sa := &SnapchatAPI{Label: "browser-session"}
	msg := sa.normalizeRemoteMessageDirection("chat-1", sidecar.Message{
		ID:       "m1",
		AuthorID: "browser-session",
		Author:   "browser-session",
		Text:     "sent from Snapchat Web",
	})
	if !msg.Outgoing {
		t.Fatal("browser-session-authored message should be treated as outgoing")
	}
	if msg.Author != "You" {
		t.Fatalf("author = %q, want You", msg.Author)
	}
}

func TestNormalizeAPIMessageDirectionTreatsSavedSelfIDAsSelf(t *testing.T) {
	db, err := store.New(filepath.Join(t.TempDir(), "state.sqlite"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if err = db.UpsertAPISyncState(store.APISyncState{
		UserID:            "browser-session",
		SelfUserID:        "7c4091a5-5231-441c-9c41-a80dfb6e805f",
		ConversationState: map[string]int64{},
	}); err != nil {
		t.Fatal(err)
	}
	sa := &SnapchatAPI{
		Label:     "browser-session",
		Connector: &SnapchatConnector{store: db},
	}
	msg := sa.normalizeAPIMessageDirection("chat-1", snapapi.Message{
		ID:       "m2",
		AuthorID: "7c4091a5-5231-441c-9c41-a80dfb6e805f",
		Author:   "Cole",
		Text:     "sent from Snapchat mobile",
	})
	if !msg.Outgoing {
		t.Fatal("saved-self authored API message should be treated as outgoing")
	}
}

func TestIsThisUserRecognizesSavedSelfID(t *testing.T) {
	db, err := store.New(filepath.Join(t.TempDir(), "state.sqlite"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if err = db.UpsertAPISyncState(store.APISyncState{
		UserID:            "browser-session",
		SelfUserID:        "7c4091a5-5231-441c-9c41-a80dfb6e805f",
		ConversationState: map[string]int64{},
	}); err != nil {
		t.Fatal(err)
	}
	sa := &SnapchatAPI{
		Label:     "browser-session",
		Connector: &SnapchatConnector{store: db},
	}
	if !sa.IsThisUser(nil, makeUserID("7c4091a5-5231-441c-9c41-a80dfb6e805f")) {
		t.Fatal("saved Snapchat self ID should be recognized as this user")
	}
}

func TestDisappearingSettingForMessageSkipsSavedMessages(t *testing.T) {
	sa := &SnapchatAPI{chatDisappearAfter: map[string]int64{"chat-1": 10}}
	got := sa.disappearingSettingForMessage("chat-1", sidecar.Message{
		ID:                    "m1",
		Text:                  "unsaved",
		DisappearAfterSeconds: 20,
	})
	if got.Timer != 20*time.Second {
		t.Fatalf("message disappearing timer = %s, want 20s", got.Timer)
	}
	got = sa.disappearingSettingForMessage("chat-1", sidecar.Message{
		ID:    "m2",
		Text:  "saved",
		Saved: true,
	})
	if got.Timer != 0 {
		t.Fatalf("saved message got disappearing timer %s", got.Timer)
	}
	got = sa.disappearingSettingForMessage("chat-1", sidecar.Message{
		ID:   "m3",
		Text: "chat default",
	})
	if got.Timer != 10*time.Second {
		t.Fatalf("chat disappearing timer = %s, want 10s", got.Timer)
	}
}

func TestShouldQueueMessageEditDetectsDecryptedBodyLater(t *testing.T) {
	if !shouldQueueMessageEdit(&store.MessageState{
		Text: "Snapchat message unavailable",
		Kind: "chat",
	}, sidecar.Message{Text: "now decoded"}) {
		t.Fatal("expected plaintext replacement to queue a Matrix edit")
	}
}

func TestShouldQueueMessageEditSkipsDuplicatesAndEmptyBodies(t *testing.T) {
	if shouldQueueMessageEdit(nil, sidecar.Message{Text: "new"}) {
		t.Fatal("nil baseline should not queue an edit")
	}
	if shouldQueueMessageEdit(&store.MessageState{Text: "same", Kind: "chat"}, sidecar.Message{Text: " same "}) {
		t.Fatal("same normalized text should not queue an edit")
	}
	if shouldQueueMessageEdit(&store.MessageState{Text: "old", Kind: "chat"}, sidecar.Message{}) {
		t.Fatal("empty replacement should not queue an edit")
	}
}

func TestShouldQueueMessageEditSkipsSnapAndMediaRows(t *testing.T) {
	for _, state := range []*store.MessageState{
		{Text: "New Snap", Kind: "snap"},
		{Text: "photo.jpg", Kind: "media"},
		{Text: "caption", Kind: "chat", HasMedia: true},
	} {
		if shouldQueueMessageEdit(state, sidecar.Message{Text: "decoded"}) {
			t.Fatalf("state %+v should not queue an ordinary text edit", state)
		}
	}
}

func TestShouldSendReadReceiptToSnapchatSkipsExactUnknownTargets(t *testing.T) {
	if (&SnapchatAPI{}).shouldSendReadReceiptToSnapchat("chat-1", 123, true) {
		t.Fatal("exact read receipt with no stored baseline should be skipped")
	}
}

func TestShouldSendReadReceiptToSnapchatAllowsStoredText(t *testing.T) {
	db, err := store.New(filepath.Join(t.TempDir(), "state.sqlite"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if err = db.UpsertMessages([]store.MessageState{{
		PortalKey:  "chat-1",
		RemoteID:   "123",
		Text:       "hello",
		Kind:       "chat",
		LastSeenAt: time.Now(),
	}}); err != nil {
		t.Fatal(err)
	}
	sa := &SnapchatAPI{Connector: &SnapchatConnector{store: db}}
	if !sa.shouldSendReadReceiptToSnapchat("chat-1", 123, true) {
		t.Fatal("stored chat text should be safe for read receipt")
	}
}

func TestShouldSendReadReceiptToSnapchatSkipsSnapAndMediaTargets(t *testing.T) {
	db, err := store.New(filepath.Join(t.TempDir(), "state.sqlite"))
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if err = db.UpsertMessages([]store.MessageState{
		{PortalKey: "chat-1", RemoteID: "123", Text: "New Snap", Kind: "snap", LastSeenAt: time.Now()},
		{PortalKey: "chat-1", RemoteID: "124", Text: "photo.jpg", Kind: "media", LastSeenAt: time.Now()},
		{PortalKey: "chat-1", RemoteID: "125", Text: "caption", Kind: "chat", HasMedia: true, LastSeenAt: time.Now()},
	}); err != nil {
		t.Fatal(err)
	}
	sa := &SnapchatAPI{Connector: &SnapchatConnector{store: db}}
	for _, messageID := range []int64{123, 124, 125} {
		if sa.shouldSendReadReceiptToSnapchat("chat-1", messageID, true) {
			t.Fatalf("message %d should be skipped for safe read receipts", messageID)
		}
	}
}
